Change config location, check directories

diff --git a/libsndfile.SlackBuild b/libsndfile.SlackBuild
--- a/libsndfile.SlackBuild
+++ b/libsndfile.SlackBuild
@@ -1,60 +1,84 @@
 #!/bin/sh
 #
-# SlackBuild for libsndfile
+# Slackware build script for libsndfile
 # Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Visit SlackPack at http://sotirov-bg.net/slackpack/
 #
 
-. ../slack-package.conf
+. /etc/slack-package.conf
 
 NAME=libsndfile
 VERSION=1.0.17
-BUILD=1
+BUILD=2
+ARCH=${ARCH:-i486}
 
-cd $TMP
-tar -zxvf $CWD/$NAME-$VERSION.tar.gz
+CWD=${CWD:-`pwd`}
+TMP=${TMP:-/tmp}
+
+if [ ! -e $TMP ]; then
+  mkdir -p $TMP # location to build the source
+fi
+
 SRC=$TMP/$NAME-$VERSION
+if [ -e $SRC -a -d $SRC ]; then
+  echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+  exit 1
+fi
+
+PKG=$TMP/package-$NAME
+if [ -e $PKG -a -d $PKG ]; then
+  echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
+  exit 2
+fi
+mkdir -p $PKG
+
+# Extract the sources
+cd $TMP
+tar -zxvf $CWD/$NAME-$VERSION.tar.gz || exit 1
 cd $SRC
 fix_source
 
+# Note: Doesn't compiles with the new version of flac
 CFLAGS=$SLKCFLAGS \
 CXXFLAGS=$SLKCFLAGS \
 ./configure --build=$ARCH-slackware-linux \
             --host=$ARCH-slackware-linux \
             --prefix=/usr \
-	    --mandir=/usr/man \
-	    --enable-shared=yes \
-	    --enable-static=no
+            --sysconfdir=/etc \
+            --mandir=/usr/man \
+            --enable-shared=yes \
+            --enable-static=no \
+            --disable-flac || exit 2
 
-make || exit 1
-
-PKG="$TMP/package-$NAME"
-mkdir -p $PKG
-
-make -e DESTDIR=$PKG install
+make -j4 || exit 3
+make DESTDIR=$PKG install || exit 4
 
 bin_perms $PKG
 ( cd $PKG; strip_bin; strip_lib )
 ( cd $SRC; create_docs $PKG $NAME-$VERSION )
 gzip_man $PKG
 
-mkdir -p $PKG/install
-install -m 644 $CWD/slack-desc     $PKG/install
-install -m 644 $CWD/slack-required $PKG/install
+# Copy service info
+install -m 755 -d $PKG/install
+install -m 644 $CWD/slack-desc     $PKG/install/slack-desc
+install -m 644 $CWD/slack-required $PKG/install/slack-required
 
-mkdir -p $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION
+SBDIR=$PKG/usr/src/slackbuilds/$NAME-$VERSION
+install -m 755 -d $SBDIR
+install -m 644 $CWD/slack-desc       $SBDIR/slack-desc
+install -m 644 $CWD/slack-required   $SBDIR/slack-required
+install -m 644 $CWD/$NAME.SlackBuild $SBDIR/$NAME.SlackBuild
 
-cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
+cd $PKG
 makepkg -l y -c n $PKG_DIR/$PKGNAME.tgz
 cd $PKG_DIR
 md5sum $PKGNAME.tgz > $PKGNAME.tgz.md5
-cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
+cp $CWD/slack-desc $PKGNAME.txt
 
-if [ "$1" == "--cleanup" ]; then
-  rm -r $SRC
-  rm -r $PKG
+# Clean up (optionally)
+if [ "$1" = "--cleanup" ]; then
+  rm -rf $SRC
+  rm -rf $PKG
 fi
 
